### ISSUE TITLE
Без асма нормально пофиксить!

### ISSUE THREAD

**Issue by Zaxar163** [RedServer/PRTweaker#1]
Ещё бы пихнули javassist, просто форкнуть пофиксить и pull, нет надо делать велосипед. А от малейшего изменения классов ломается!

**Comment by TheAndrey** [comment]
1. Научись доходчиво формулировать свои мысли.
2. Дарёному коню в зубы не смотрят. Не нравится? Сделай лучше!
3. Я не силён в **scala**.
4. Чтобы собрать мод, нужно ремонтировать сценарий сборки. Используемые модами репозитории регулярно умирают. Поэтому патчер сделать выходит проще.
